[dns]
host = "0.0.0.0"
port = 5353
upstream_servers = ["8.8.8.8:53", "1.1.1.1:53", "208.67.222.222:53"]
cache_size = 10000
cache_ttl = 300
enable_ai_features = true

[web]
host = "0.0.0.0"
port = 8080
cors_origins = ["*"]
static_dir = "./frontend/dist"

[database]
uri = "mongodb://localhost:27017"
database_name = "bhai_dns"
max_pool_size = 100

[redis]
uri = "redis://localhost:6379"
db = 0
max_connections = 50
key_prefix = "bhai_dns:"

[ai]
threat_detection = true
typo_correction = true
domain_analysis = true

[analytics]
enabled = true
retention_days = 30
metrics_port = 9090

[auth]
jwt_secret = "your-super-secret-key-change-in-production"
token_expiry = 3600
enable_registration = true

[performance]
worker_threads = 0
connection_timeout = 30
query_timeout = 5
max_connections = 10000
rate_limit_per_minute = 1000