version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: bhai-dns-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: bhai_dns
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - bhai-dns-network

  # Rust Backend
  bhai-dns-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bhai-dns-backend
    restart: unless-stopped
    environment:
      - DATABASE_URI=mongodb://admin:password@mongodb:27017/bhai_dns?authSource=admin
      - RUST_LOG=info
    ports:
      - "5353:5353/udp"  # DNS Server
      - "8080:8080"      # Web API
      - "9090:9090"      # Metrics
    depends_on:
      - mongodb
    volumes:
      - ./config.toml:/app/config.toml:ro
    networks:
      - bhai-dns-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # React Frontend
  bhai-dns-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bhai-dns-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - bhai-dns-backend
    networks:
      - bhai-dns-network
    environment:
      - REACT_APP_API_URL=http://localhost:8080

  # Redis for caching and rate limiting
  redis:
    image: redis:7-alpine
    container_name: bhai-dns-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - bhai-dns-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Prometheus for monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: bhai-dns-prometheus
    restart: unless-stopped
    ports:
      - "9091:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - bhai-dns-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'

  # Grafana for dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: bhai-dns-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    networks:
      - bhai-dns-network
    depends_on:
      - prometheus

networks:
  bhai-dns-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
  prometheus_data:
  grafana_data: